version: '2'

services:

  api:
    build:
      context: .
    volumes:
      - .:/roadcaptain
    working_dir: /roadcaptain
    command: "bash docker-run.sh"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - RDCPT_DB=roadcaptain
      - LISTEN_PORT=3000
      #secret envvars
      - MAPS_KEY
  app:
    build:
      context: ./src/client
    volumes:
      - .:/roadcaptain
    working_dir: /roadcaptain/src/client
    command: "bash docker-run.sh"
  proxy:
    image: node:carbon
    volumes:
      - .:/roadcaptain
    working_dir: /roadcaptain/src/proxy
    command: "bash docker-proxy.sh"
    ports:
      - "80:80"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
